package com.dbdeployer.service;

import com.dbdeployer.deploy.DatabaseCatalog;
import com.dbdeployer.deploy.DockerDeployEngine;
import com.dbdeployer.model.DbType;
import com.dbdeployer.model.DeployedContainer;
import com.dbdeployer.model.DeploymentConfig;
import com.dbdeployer.model.InstanceStatus;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

/**
 * Renders the current set of managed instances as a portable {@code docker-compose.yml}.
 *
 * <p>Walks every non-REMOVED, non-system, non-template {@link DeployedContainer} and emits one
 * Compose service block per instance, reusing the same image tag, port bindings, environment
 * variables ({@link DockerDeployEngine#resolveEnv}) and volume path the live deploy path uses.
 *
 * <p>Volumes are emitted as <em>named</em> volumes (not host bind mounts) so the output is portable
 * across machines. The result is a starting point, not a production spec — {@code version: "3.9"}
 * is pinned for the widest compatibility (roadmap §6 Phase 1).
 */
@Slf4j
@Service
public class ComposeExportService {

  private final DbInstanceService instanceService;
  private final DockerDeployEngine docker;

  public ComposeExportService(DbInstanceService instanceService, DockerDeployEngine docker) {
    this.instanceService = instanceService;
    this.docker = docker;
  }

  /** Builds a complete {@code docker-compose.yml} document for all exportable instances. */
  public String exportYaml() {
    List<DeployedContainer> exportable = exportableContainers();

    StringBuilder services = new StringBuilder();
    StringBuilder namedVolumes = new StringBuilder();
    Set<String> usedServiceKeys = new TreeSet<>();

    for (DeployedContainer container : exportable) {
      DeploymentConfig config = container.getConfig();
      DatabaseCatalog.DbDefinition def = DatabaseCatalog.get(config.getDbType());
      if (def == null || def.dockerImage() == null) {
        continue; // not a deployable Docker image (e.g. H2 system store)
      }

      String serviceKey = uniqueServiceKey(config.getName(), usedServiceKeys);
      appendService(services, namedVolumes, serviceKey, container, config, def);
    }

    StringBuilder out = new StringBuilder();
    out.append("# Generated by Port Wrangler — a starting point, not a production spec.\n");
    out.append("version: \"3.9\"\n\n");

    if (services.isEmpty()) {
      out.append("services: {}\n");
      return out.toString();
    }

    out.append("services:\n").append(services);
    if (!namedVolumes.isEmpty()) {
      out.append("\nvolumes:\n").append(namedVolumes);
    }
    return out.toString();
  }

  /**
   * Distinct, live (non-REMOVED) instances owned by the user — one per config, RUNNING preferred.
   */
  private List<DeployedContainer> exportableContainers() {
    // Keyed by config id; first writer wins, so order containers by status priority first.
    Map<String, DeployedContainer> byConfig = new LinkedHashMap<>();
    instanceService.listAll().stream()
        .filter(c -> c.getConfig() != null)
        .filter(c -> c.getStatus() != InstanceStatus.REMOVED)
        .filter(c -> !c.getConfig().isSystem())
        .filter(c -> !c.getConfig().isTemplate())
        .sorted((a, b) -> Integer.compare(statusRank(a.getStatus()), statusRank(b.getStatus())))
        .forEach(c -> byConfig.putIfAbsent(c.getConfig().getId(), c));
    return new ArrayList<>(byConfig.values());
  }

  /** Lower rank = preferred when multiple containers exist for one config. */
  private static int statusRank(InstanceStatus status) {
    return switch (status) {
      case RUNNING -> 0;
      case RESTARTING, DEPLOYING -> 1;
      case STOPPED -> 2;
      default -> 3;
    };
  }

  private void appendService(
      StringBuilder services,
      StringBuilder namedVolumes,
      String serviceKey,
      DeployedContainer container,
      DeploymentConfig config,
      DatabaseCatalog.DbDefinition def) {

    int containerPort =
        container.getContainerPort() > 0 ? container.getContainerPort() : def.defaultPort();

    services.append("  ").append(serviceKey).append(":\n");
    services
        .append("    image: ")
        .append(yaml(def.dockerImage() + ":" + config.getVersion()))
        .append("\n");
    services.append("    container_name: ").append(yaml(container.getContainerName())).append("\n");
    services.append("    restart: unless-stopped\n");

    // ── ports (main binding + multi-port special cases mirroring createContainer) ──
    services.append("    ports:\n");
    services
        .append("      - ")
        .append(yaml(config.getHostPort() + ":" + containerPort))
        .append("\n");
    for (String extra : extraPortMappings(config.getDbType())) {
      services.append("      - ").append(yaml(extra)).append("\n");
    }

    // ── environment ──
    List<String> env = docker.resolveEnv(config);
    if (!env.isEmpty()) {
      services.append("    environment:\n");
      for (String kv : env) {
        int eq = kv.indexOf('=');
        String key = eq >= 0 ? kv.substring(0, eq) : kv;
        String value = eq >= 0 ? kv.substring(eq + 1) : "";
        services.append("      ").append(key).append(": ").append(yaml(value)).append("\n");
      }
    }

    // ── volumes (named volume for portability) ──
    if (def.dataVolumePath() != null) {
      String volName = serviceKey + "-data";
      services.append("    volumes:\n");
      services.append("      - ").append(yaml(volName + ":" + def.dataVolumePath())).append("\n");
      namedVolumes.append("  ").append(volName).append(":\n");
    }
  }

  /** Additional published ports that {@code createContainer} binds beyond the primary port. */
  private static List<String> extraPortMappings(DbType type) {
    return switch (type) {
      case NEO4J -> List.of("7687:7687"); // bolt
      case CLICKHOUSE -> List.of("8123:8123"); // http
      case KAFKA -> List.of("9093:9093"); // controller
      default -> List.of();
    };
  }

  private static String uniqueServiceKey(String name, Set<String> used) {
    String base = name.toLowerCase().replaceAll("[^a-z0-9_-]", "-").replaceAll("(^-+)|(-+$)", "");
    if (base.isBlank()) base = "service";
    String key = base;
    int n = 2;
    while (!used.add(key)) {
      key = base + "-" + n++;
    }
    return key;
  }

  /**
   * Renders a scalar as a safely double-quoted YAML string. Always quoting avoids ambiguity with
   * values that contain {@code :}, {@code //}, leading zeros, or look like booleans/numbers.
   */
  private static String yaml(String value) {
    if (value == null) return "\"\"";
    String escaped = value.replace("\\", "\\\\").replace("\"", "\\\"");
    return "\"" + escaped + "\"";
  }
}
